# See https://prek.j178.dev/ for more information
# yaml-language-server: $schema=https://raw.githubusercontent.com/j178/prek/refs/heads/master/prek.schema.json
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  # Self checks
  - repo: meta
    hooks:
      #- id: check-hooks-apply
      - id: check-useless-excludes

  # Text files
  - repo: builtin
    hooks:
      # plaintext fixers
      - id: trailing-whitespace
        exclude: '\.(log|patch)$'
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      # config syntax checkers
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      # filesystems checkers
      #- id: check-symlinks
      - id: check-executables-have-shebangs

  # Spell checker
  - repo: https://github.com/crate-ci/typos
    rev: 8a48f81b6c64dcfea44b3633223084c4be58ac5f # frozen: v1.49.0
    hooks:
      - id: typos
      # From https://github.com/crate-ci/typos/issues/1473
      - id: typos
        alias: typos-commit-msg
        args: [--force-exclude]
        stages:
          - commit-msg

  # Markdown formatter
  - repo: https://github.com/hukkin/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547 # frozen: 1.0.0
    hooks:
      - id: mdformat
        # https://mdformat.readthedocs.io/en/stable/users/plugins.html
        additional_dependencies:
          - mdformat-config
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-shfmt
          - mdformat-myst
          - mdformat-front-matters
        args: [--strict-front-matter]
        exclude: 'README\.md|CHANGELOG\.md'

  # Update README examples
  - repo: https://github.com/zimbatm/mdsh
    rev: c78e9090d1450a748d4a21a194d458ee51ad9e7f # 0.9.2+
    hooks:
      - id: mdsh
        args: [README.md]
        pass_filenames: false
        always_run: true

  # Shell formatter
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 05c1426671b9237fb5e1444dd63aa5731bec0dfb # frozen: v3.13.1-1
    hooks:
      - id: shfmt

  # Shell linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  # Python formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2 # frozen: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # TOML formatter
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 8fbf394367746670a106c96680aaacace367d5e2 # frozen: v1.2.6
    hooks:
      - id: tombi-format
      - id: tombi-lint

  # Check PKGBUILD and .SCRINFO
  - repo: local
    hooks:
      # Standard PKGBUILD analysis
      - id: namcap
        name: namcap
        language: system
        entry: namcap --info
        files: PKGBUILD
      # Newer PKGBUILD linter from ALPM
      - id: alpm-lint-check
        name: alpm-lint-check
        language: system
        entry: alpm-lint check --level suggest --verbose
        files: 'PKGBUILD|.SRCINFO'
        pass_filenames: 1
      # Guarantee up-to-date .SRCINFO
      - id: makepkg-printsrcinfo
        name: makepkg-printsrcinfo
        language: system
        shell: sh
        entry: makepkg --printsrcinfo > .SRCINFO
        files: 'PKGBUILD|.SRCINFO'
        pass_filenames: false
      # Validate generated .SRCINFO
      - id: alpm-srcinfo-validate
        name: alpm-srcinfo-validate
        language: system
        entry: alpm-srcinfo validate
        files: .SRCINFO
        pass_filenames: 1

  # License linter
  - repo: https://codeberg.org/fsfe/reuse-tool
    rev: a1bb792acda6fd0724936b4ebbdbc8eceb9c0459 # frozen: v6.2.0
    hooks:
      - id: reuse

minimum_prek_version: 0.4.13
