# See https://prek.j178.dev/ for more information
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  # Self checks
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # Text files
  - repo: builtin
    hooks:
      # plaintext fixers
      - id: trailing-whitespace
        exclude: '\.(log|patch|ghostty)$'
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      # config syntax checkers
      - id: check-yaml
      - id: check-toml
      # filesystems checkers
      #- id: check-symlinks
      - id: check-executables-have-shebangs

  # Markdown formatter
  - repo: https://github.com/hukkin/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547 # frozen: 1.0.0
    hooks:
      - id: mdformat
        # https://mdformat.readthedocs.io/en/stable/users/plugins.html
        additional_dependencies:
          - mdformat-config
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-shfmt
          - mdformat-myst
          - mdformat-front-matters
        args: [--strict-front-matter]

  # Shell formatter
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 05c1426671b9237fb5e1444dd63aa5731bec0dfb # frozen: v3.13.1-1
    hooks:
      - id: shfmt

  # Shell linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  # Python formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 77039ccbba72c8aede339c5f8ae29b42aced0a2e  # frozen: v0.15.18
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # TOML formatter
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 63b8dbce992ca0fa201239acde684c053bf05fd1  # frozen: v1.1.5
    hooks:
      - id: tombi-format
      - id: tombi-lint

minimum_prek_version: 0.4.5
